### ISSUE TITLE
Datei ist beschädigt

### ISSUE THREAD

**Issue by Berovowilare** [scientific-tool-set/scitos#41]
Hallo 

Ich konnte Scitos nicht öffnen.

<img width="725" alt="Bildschirmfoto 2023-12-08 um 13 22 32" src="https://github.com/scientific-tool-set/scitos/assets/36891575/c60c27a5-19cf-4649-b94c-4efc04c7d242">

Auch das App Icon ist leer. Siehe Bild oben links.

Danke

**Comment by CarstenWickner** [comment]
Hi @Berovowilare,

Did you recently perform a MacOS update? Did it work before and now stopped or did it never work for you?

**Comment by Berovowilare** [comment]
Hello Carsten
No I just discovered this App form a mention of a Bible software forum. I searched for it and tried to use it. I haven't used this tool in the past. I'm on Ventura, as other tools like the LingTreeConstructor and language tools from Ulrik don't work on Sonoma (Intel Mac). 
To answer your question, it did never work.

**Comment by Berovowilare** [comment]
Just something flew my mind.
I had in the past a similar issue with another app. The USFM Converter. The developer told me to go to the Terminal and paste "xattr -dr com.apple.quarantine /Applications/USFM\ Converter.app" in it. Without the quotes. In this app the issue was not solved. As it has others too. But maybe this works with yours.

**Comment by CarstenWickner** [comment]
HI @Berovowilare,

That's what I recommended in this old question about the same thing: https://github.com/scientific-tool-set/scitos/discussions/37
> Issue 1: “SciToS” is damaged and can’t be opened. You should move it to the Bin.
> 
> In some cases, macOS will show this rather misleading message, which is just a harsh way of letting you know, that the application was put into "quarantine".
> However, if you do trust the application you can lift that "quarantine" via the following steps:
> 
> 1. Open a Terminal (or another console). By default, this may open in your user's home folder.
> 2. Navigate to the directory where the unpacked `SciToS.app` is – via the `cd` command, e.g. `cd Downloads/target` if you simply unpacked it directly in your Downloads directory.
> 3. Then lift the quarantine with the following command:
```
sudo xattr -r -d com.apple.quarantine SciToS.app
```
> 4. Enter your password to confirm the elevated access of the "super-user-do"/`sudo` command.
> 5. Now you can start close the Terminal and start using the SciToS.app.

**Comment by Berovowilare** [comment]
Thanks.
