### ISSUE TITLE
Issue: result table "Detail sequence"/"Detail pattern"

### ISSUE THREAD

**Issue by CaroWickner** [scientific-tool-set/scitos#5]
When having a lot of interviews, there is no space to view the result table under "Detail sequence"/"Detail pattern" and most of the boxes show (...). However, there is no problem to view the content of the boxes after export to spreadsheet.

**Comment by CaroWickner** [comment]
When having a lot of interviews, there is no space to view the result table under "Detail sequence"/"Detail pattern" and most of the boxes show (...). However, there is no problem to view the content of the boxes after export to spreadsheet.

**Comment by CarstenEnglert** [comment]
This has been fixed as of version 1.2.0.
